# Notebook 01 — Collecte des données

Objectif : télécharger les prix historiques des actions choisies et de l'indice CAC 40.

À la fin de ce notebook, on obtient :
- `data/raw/prix_actions.csv`

In [4]:
# TODO importer les bibliothèques
import os
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

os.makedirs("../data/brut", exist_ok=True)
os.makedirs("../data/obtenue", exist_ok=True)
os.makedirs("../figures", exist_ok=True)

## 1. Liste des actions

On choisit 15 actions françaises .

In [12]:
# TODO à faire par tareq
campanies = [
    "TTE.PA",   # TotalEnergies
    "SU.PA",    # Schneider Electric
    "MC.PA",    # LVMH
    "AI.PA",    # Air Liquide
    "SAN.PA",   # Sanofi
    "AIR.PA",   # Airbus
    "SAF.PA",   # Safran
    "BNP.PA",   # BNP Paribas
    "OR.PA",    # L'Oréal
    "CS.PA",    # AXA
    "DG.PA",    # Vinci
    "EL.PA",    # EssilorLuxottica
    "RMS.PA",   # Hermès
    "KER.PA",   # Kering
    "ACA.PA"    # Crédit Agricole
]

indice = "^FCHI"
all_campanies = campanies + [indice]

noms_actions = {
    "TTE.PA": "TotalEnergies",
    "SU.PA": "Schneider Electric",
    "MC.PA": "LVMH",
    "AI.PA": "Air Liquide",
    "SAN.PA": "Sanofi",
    "AIR.PA": "Airbus",
    "SAF.PA": "Safran",
    "BNP.PA": "BNP Paribas",
    "OR.PA": "L'Oréal",
    "CS.PA": "AXA",
    "DG.PA": "Vinci",
    "EL.PA": "EssilorLuxottica",
    "RMS.PA": "Hermès",
    "KER.PA": "Kering",
    "ACA.PA": "Crédit Agricole",
    "^FCHI": "CAC 40"
}

## 2. Téléchargement des données

In [13]:
# TODO à faire par tareq
data = yf.download(
    all_campanies,
    start="2020-01-01",
    end="2025-12-31",
    auto_adjust=True,
    progress=True
)

data.head()

[*********************100%***********************]  16 of 16 completed

Price          Close                                                          \
Ticker        ACA.PA      AI.PA      AIR.PA     BNP.PA      CS.PA      DG.PA
Date
2020-01-02  8.961940  93.452423  122.495934  37.874336  18.182152  79.617821
2020-01-03  8.907563  93.157387  122.972984  37.421940  18.189293  79.123405
2020-01-06  8.819201  92.530441  122.440895  37.238152  17.950054  78.724678
2020-01-07  8.798811  92.124763  121.101440  37.224007  18.060747  78.182404
2020-01-08  8.839593  92.198517  123.284927  37.308838  18.053604  79.681625

Price                                                       ...  Volume  \
Ticker           EL.PA      KER.PA       MC.PA       OR.PA  ...   EL.PA
Date                                                        ...
2020-01-02  122.481544  514.596680  380.116272  242.358582  ...  533765
2020-01-03  122.078354  517.092224  380.070984  242.083344  ...  515016
2020-01-06  121.943962  508.400940  376.488800  241.257767  ...  567758
2020-01-07  122.795135  513.133850  377.259705  238.138840  ...  592386
2020-01-08  124.452728  513.994202  379.798920  239.606567  ...  396153

Price                                                                         \
Ticker      KER.PA   MC.PA   OR.PA RMS.PA  SAF.PA   SAN.PA    SU.PA   TTE.PA
Date
2020-01-02  178651  347226  351300  42679  727750  1720684  1084445  4326276
2020-01-03  159019  291716  292884  33911  558276  1534465   971960  4960724
2020-01-06  176511  363953  367820  44451  713375  2356637  1080758  7596924
2020-01-07  201861  363885  508141  50766  730793  1975503  1025424  5380020
2020-01-08  201239  360741  431996  34952  762013  1718950  1124353  4922510

Price
Ticker         ^FCHI
Date
2020-01-02  63958300
2020-01-03  60488000
2020-01-06  69063700
2020-01-07  69593800
2020-01-08  71431600

[5 rows x 80 columns]

## 3. Extraction des prix de clôture

In [14]:
# TODO faire par tareq
prix = data["Close"].copy()

# On supprime les lignes complètement vides si elles existent.
prix = prix.dropna(how="all")

# On sauvegarde les données brutes.
prix.to_csv("../data/brut/prix_actions.csv")

prix.head()

Ticker,ACA.PA,AI.PA,AIR.PA,BNP.PA,CS.PA,DG.PA,EL.PA,KER.PA,MC.PA,OR.PA,RMS.PA,SAF.PA,SAN.PA,SU.PA,TTE.PA,^FCHI
Date,,,,,,,,,,,,,,,,
2020-01-02,8.961940,93.452423,122.495934,37.874336,18.182152,79.617821,122.481544,514.596680,380.116272,242.358582,634.294556,132.262634,71.409309,81.937683,33.182526,6041.500000
2020-01-03,8.907563,93.157387,122.972984,37.421940,18.189293,79.123405,122.078354,517.092224,380.070984,242.083344,638.453796,132.647110,71.852554,81.726372,33.558887,6044.160156
2020-01-06,8.819201,92.530441,122.440895,37.238152,17.950054,78.724678,121.943962,508.400940,376.488800,241.257767,633.160156,131.157227,72.303703,81.620712,34.044849,6013.589844
2020-01-07,8.798811,92.124763,121.101440,37.224007,18.060747,78.182404,122.795135,513.133850,377.259705,238.138840,641.100647,132.358749,72.050423,81.286125,33.822124,6012.350098
2020-01-08,8.839593,92.198517,123.284927,37.308838,18.053604,79.681625,124.452728,513.994202,379.798920,239.606567,646.772583,132.166504,72.295784,81.497444,33.909870,6031.000000

## 4. Vérification rapide

On vérifie les dimensions et les valeurs manquantes.

In [ ]:
# TODO faire par karim

## 5. Visualisation rapide des prix normalisés

In [ ]:
# TODO faire par karim